project:
  type: website
  output-dir: docs

website:
  title: "Adam Hartley"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - CSC_480/CSC_480.qmd
      - CSC_226/CSC_226.qmd
      - CSC_108/CSC_108.qmd


format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

