---
title: "DSC_360_private"
---

+---------+---------+--------------------------------------+---------+-----------------------------------------------+---------+------------------------------------+
| Week \# | Date    | Monday                               | Date    | Wednesday                                     | Date    | Friday                             |
+=========+=========+======================================+=========+===============================================+=========+====================================+
| 1       | 8-26    | Intro                                | 8-28    | Python Libraries                              | 8-30    | Pandas                             |
|         |         |                                      |         |                                               |         |                                    |
|         |         |                                      |         | **Act. 1**                                    |         | **Act. 2**                         |
+---------+---------+--------------------------------------+---------+-----------------------------------------------+---------+------------------------------------+
| 2       | 9-2     | Labor Day                            | 9-4     | Data Type Conversion                          | 9-6     | Exporting Data / Visualization     |
|         |         |                                      |         |                                               |         |                                    |
|         |         | **No Class**                         |         | Aggregation and Grouping                      |         | **Act. 3**                         |
+---------+---------+--------------------------------------+---------+-----------------------------------------------+---------+------------------------------------+
| 3       | 9-9     | Types of Graph                       | 9-11    | Seaborn                                       | 9-13    | Dataframes                         |
|         |         |                                      |         |                                               |         |                                    |
|         |         | Components of Graphs                 |         | Types of Graphs                               |         | Grouped Data                       |
|         |         |                                      |         |                                               |         |                                    |
|         |         |                                      |         | **Act. 4**                                    |         | **Act. 5**                         |
+---------+---------+--------------------------------------+---------+-----------------------------------------------+---------+------------------------------------+
| 4       | 9-16    | Modifying Graphs                     | 9-18    | Hadoop                                        | 9-20    | Spark                              |
|         |         |                                      |         |                                               |         |                                    |
|         |         | Exporting Data                       |         |                                               |         |                                    |
|         |         |                                      |         |                                               |         |                                    |
|         |         | **Act. 6-7**                         |         |                                               |         |                                    |
+---------+---------+--------------------------------------+---------+-----------------------------------------------+---------+------------------------------------+
| 5       | 9-23    | Parquet                              | 9-25    | Handling Unstructured Data                    | 9-27    | Spark Dataframes                   |
|         |         |                                      |         |                                               |         |                                    |
|         |         |                                      |         | **Act. 8**                                    |         |                                    |
+---------+---------+--------------------------------------+---------+-----------------------------------------------+---------+------------------------------------+
| 6       | 9-30    | Exploring Spark Dataframes           | 10-2    | Data Manipulation with Spark Dataframes       | 10-4    | Graphs in Spark                    |
|         |         |                                      |         |                                               |         |                                    |
|         |         | **Act. 9**                           |         | **Act. 10**                                   |         | **Act. 11**                        |
+---------+---------+--------------------------------------+---------+-----------------------------------------------+---------+------------------------------------+
| 7       | 10-7    | Missing Values                       | 10-9    | Handling Missing Values with Spark Dataframes | 10-11   | Correlation                        |
|         |         |                                      |         |                                               |         |                                    |
|         |         |                                      |         |                                               |         | **Act. 12**                        |
+---------+---------+--------------------------------------+---------+-----------------------------------------------+---------+------------------------------------+
| 8       | 10-14   | Review                               | 10-16   | **Midterm Exam**                              | 10-18   | Fall Break                         |
|         |         |                                      |         |                                               |         |                                    |
|         |         |                                      |         |                                               |         | **No Class**                       |
+---------+---------+--------------------------------------+---------+-----------------------------------------------+---------+------------------------------------+
| 9       | 10-21   | Defining Business Problems           | 10-23   | Translating Business Problems                 | 10-25   | Standard Approach                  |
|         |         |                                      |         |                                               |         |                                    |
|         |         |                                      |         |                                               |         | Data Science Life Cycle            |
|         |         |                                      |         |                                               |         |                                    |
|         |         |                                      |         |                                               |         | **Act. 13**                        |
+---------+---------+--------------------------------------+---------+-----------------------------------------------+---------+------------------------------------+
| 10      | 10-28   | Reproducibility in Jupyter Notebooks | 10-30   | Gathering Data Reproducibly                   | 11-1    | Code Practices and Standards       |
+---------+---------+--------------------------------------+---------+-----------------------------------------------+---------+------------------------------------+
| 11      | 11-4    | Avoiding Repetition                  | 11-6    | Reading Data in Spark                         | 11-8    | SQL Operations on Spark Dataframes |
|         |         |                                      |         |                                               |         |                                    |
|         |         | **Act. 14**                          |         | Different Data Sources                        |         |                                    |
+---------+---------+--------------------------------------+---------+-----------------------------------------------+---------+------------------------------------+
| 12      | 11-11   | Generating Statistical Relationships | 11-13   | In-class project work                         | 11-15   | In-class project work              |
|         |         |                                      |         |                                               |         |                                    |
|         |         | **Act. 15**                          |         |                                               |         |                                    |
+---------+---------+--------------------------------------+---------+-----------------------------------------------+---------+------------------------------------+
| 13      | 11-18   | In-class project work                | 11-20   | In-class project work                         | 11-22   | In-class project work              |
+---------+---------+--------------------------------------+---------+-----------------------------------------------+---------+------------------------------------+
| 14      | 11-25   | **Final Exam**                       | 11-27   | Thanksgiving                                  | 11-29   | Thanksgiving                       |
|         |         |                                      |         |                                               |         |                                    |
|         |         |                                      |         | **No Class**                                  |         | **No Class**                       |
+---------+---------+--------------------------------------+---------+-----------------------------------------------+---------+------------------------------------+
| 15      | 12-2    | Presentations                        | 12-4    | Presentations                                 | 12-6    | Presentations                      |
+---------+---------+--------------------------------------+---------+-----------------------------------------------+---------+------------------------------------+

: Tentative Schedule
